/* The following code was generated by JFlex 1.3.5 on 9/19/19, 3:25 PM */

/*
  This example comes from a short article series in the Linux 
  Gazette by Richard A. Sevenich and Christopher Lopes, titled
  "Compiler Construction Tools". The article series starts at

  http://www.linuxgazette.com/issue39/sevenich.html

  Small changes and updates to newest JFlex+Cup versions 
  by Gerwin Klein
*/

/*
  Commented By: Christopher Lopes
  File Name: lcalc.flex
  To Create: > jflex lcalc.flex

  and then after the parser is created
  > javac Lexer.java
*/
   
/* --------------------------Usercode Section------------------------ */
   
import java_cup.runtime.*;
      

/**
 * This class is a scanner generated by 
 * <a href="http://www.jflex.de/">JFlex</a> 1.3.5
 * on 9/19/19, 3:25 PM from the specification file
 * <tt>file:/home/luizsetten/Desktop/Compiladores/simple_program_sintatic_only/lcalc.flex</tt>
 */
class Lexer implements java_cup.runtime.Scanner {

  /** This character denotes the end of file */
  final public static int YYEOF = -1;

  /** initial size of the lookahead buffer */
  final private static int YY_BUFFERSIZE = 16384;

  /** lexical states */
  final public static int YYINITIAL = 0;

  /** 
   * Translates characters to character classes
   */
  final private static char [] yycmap = {
     0,  0,  0,  0,  0,  0,  0,  0,  0,  5,  3,  0,  5,  4,  0,  0, 
     0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0, 
     5,  0,  0,  0,  0,  0,  0,  0, 13, 14,  1,  9,  0, 10,  0,  2, 
     6,  7,  7,  7,  7,  7,  7,  7,  7,  7,  0,  0, 15, 16, 17,  0, 
     0,  8,  8,  8,  8,  8,  8,  8,  8,  8,  8,  8,  8,  8,  8,  8, 
     8,  8,  8,  8,  8,  8,  8,  8,  8,  8,  8, 11,  0, 12,  0,  8, 
     0, 23,  8, 20, 34, 18, 30, 26,  8, 28,  8,  8, 33, 27, 29, 25, 
    24, 35, 21, 19, 32, 31, 22,  8,  8,  8,  8,  0,  0,  0,  0,  0
  };

  /** 
   * Translates a state to a row index in the transition table
   */
  final private static int yy_rowMap [] = { 
        0,    36,    36,    72,    36,   108,    36,   144,   180,    36, 
       36,    36,    36,    36,    36,   216,    36,    36,   252,   288, 
      324,   360,   396,   432,   468,   504,   540,   576,   612,    36, 
      648,   684,   720,   756,   792,   828,   180,   864,   900,   936, 
      972,  1008,  1044,   180,  1080,  1116,  1152,  1188,  1224,   180, 
     1260,  1296,  1332,  1368,  1404,  1440,  1476,  1512,  1548,  1584, 
     1620,  1656,  1692,  1728,  1764,  1800,  1836,   180,  1872,  1908, 
      180,  1944,  1980,  2016,  2052,  2088,   180,    36,  2124,   180, 
     2160,   180,  2196,   180,  2232,  2268,  2304,   180,  2340,  2376, 
     2412,  2448,  2484,  2520,   180,  2556,  2592,  2628,  2664,  2700, 
      180,  2736,  2772,   180,  2808,   180,  2844,  2880,  2916,   180, 
      180,  2952,  2988,  3024,  3060,  3096,  3132,   180,   180,  3168, 
     3204,   180,  3240,   180
  };

  /** 
   * The packed transition table of the DFA (part 0)
   */
  final private static String yy_packed0 = 
    "\1\2\1\3\1\4\1\5\1\6\1\5\1\7\1\10"+
    "\1\11\1\12\1\13\1\14\1\15\1\16\1\17\1\20"+
    "\1\21\1\22\1\23\1\24\3\11\1\25\1\26\1\27"+
    "\2\11\1\30\1\11\1\31\2\11\1\32\1\33\1\11"+
    "\45\0\1\34\1\35\44\0\1\5\46\0\2\10\42\0"+
    "\3\11\11\0\22\11\12\0\1\36\37\0\3\11\11\0"+
    "\1\11\1\37\11\11\1\40\6\11\6\0\3\11\11\0"+
    "\1\41\21\11\6\0\3\11\11\0\16\11\1\42\3\11"+
    "\6\0\3\11\11\0\3\11\1\43\1\11\1\44\14\11"+
    "\6\0\3\11\11\0\15\11\1\45\4\11\6\0\3\11"+
    "\11\0\13\11\1\46\6\11\6\0\3\11\11\0\5\11"+
    "\1\47\4\11\1\50\2\11\1\51\1\11\1\52\2\11"+
    "\6\0\3\11\11\0\1\53\21\11\6\0\3\11\11\0"+
    "\1\54\21\11\1\55\1\0\42\55\3\35\2\0\37\35"+
    "\6\0\3\11\11\0\2\11\1\56\17\11\6\0\3\11"+
    "\11\0\16\11\1\57\2\11\1\60\6\0\3\11\11\0"+
    "\13\11\1\61\6\11\6\0\3\11\11\0\1\62\21\11"+
    "\6\0\3\11\11\0\7\11\1\63\12\11\6\0\3\11"+
    "\11\0\1\11\1\64\1\11\1\65\16\11\6\0\3\11"+
    "\11\0\12\11\1\66\3\11\1\67\3\11\6\0\3\11"+
    "\11\0\2\11\1\70\17\11\6\0\3\11\11\0\11\11"+
    "\1\71\10\11\6\0\3\11\11\0\13\11\1\72\6\11"+
    "\6\0\3\11\11\0\15\11\1\73\4\11\6\0\3\11"+
    "\11\0\12\11\1\74\7\11\1\55\1\75\1\0\41\55"+
    "\6\0\3\11\11\0\3\11\1\76\16\11\6\0\3\11"+
    "\11\0\5\11\1\77\14\11\6\0\3\11\11\0\15\11"+
    "\1\100\4\11\6\0\3\11\11\0\5\11\1\101\14\11"+
    "\6\0\3\11\11\0\10\11\1\102\11\11\6\0\3\11"+
    "\11\0\1\11\1\103\20\11\6\0\3\11\11\0\5\11"+
    "\1\104\14\11\6\0\3\11\11\0\2\11\1\105\17\11"+
    "\6\0\3\11\11\0\1\106\21\11\6\0\3\11\11\0"+
    "\5\11\1\107\14\11\6\0\3\11\11\0\1\110\1\111"+
    "\4\11\1\112\13\11\6\0\3\11\11\0\2\11\1\113"+
    "\17\11\6\0\3\11\11\0\16\11\1\114\3\11\6\0"+
    "\3\11\11\0\5\11\1\115\14\11\1\55\1\75\1\116"+
    "\41\55\6\0\3\11\11\0\1\117\21\11\6\0\3\11"+
    "\11\0\7\11\1\120\12\11\6\0\3\11\11\0\5\11"+
    "\1\121\14\11\6\0\3\11\11\0\7\11\1\122\12\11"+
    "\6\0\3\11\11\0\3\11\1\123\16\11\6\0\3\11"+
    "\11\0\7\11\1\124\12\11\6\0\3\11\11\0\12\11"+
    "\1\125\7\11\6\0\3\11\11\0\12\11\1\126\7\11"+
    "\6\0\3\11\11\0\13\11\1\127\6\11\6\0\3\11"+
    "\11\0\1\130\21\11\6\0\3\11\11\0\5\11\1\131"+
    "\14\11\6\0\3\11\11\0\5\11\1\132\14\11\6\0"+
    "\3\11\11\0\15\11\1\133\4\11\6\0\3\11\11\0"+
    "\4\11\1\134\15\11\6\0\3\11\11\0\13\11\1\135"+
    "\6\11\6\0\3\11\11\0\5\11\1\136\14\11\6\0"+
    "\3\11\11\0\7\11\1\137\12\11\6\0\3\11\11\0"+
    "\3\11\1\140\16\11\6\0\3\11\11\0\21\11\1\141"+
    "\6\0\3\11\11\0\3\11\1\142\16\11\6\0\3\11"+
    "\11\0\7\11\1\143\12\11\6\0\3\11\11\0\5\11"+
    "\1\144\14\11\6\0\3\11\11\0\5\11\1\145\14\11"+
    "\6\0\3\11\11\0\16\11\1\146\3\11\6\0\3\11"+
    "\11\0\11\11\1\147\10\11\6\0\3\11\11\0\7\11"+
    "\1\150\12\11\6\0\3\11\11\0\15\11\1\151\4\11"+
    "\6\0\3\11\11\0\5\11\1\152\14\11\6\0\3\11"+
    "\11\0\12\11\1\153\1\11\1\154\5\11\6\0\3\11"+
    "\11\0\13\11\1\155\6\11\6\0\3\11\11\0\7\11"+
    "\1\156\12\11\6\0\3\11\11\0\5\11\1\157\14\11"+
    "\6\0\3\11\11\0\5\11\1\160\14\11\6\0\3\11"+
    "\11\0\13\11\1\161\6\11\6\0\3\11\11\0\12\11"+
    "\1\162\7\11\6\0\3\11\11\0\16\11\1\163\3\11"+
    "\6\0\3\11\11\0\13\11\1\164\6\11\6\0\3\11"+
    "\11\0\12\11\1\165\7\11\6\0\3\11\11\0\11\11"+
    "\1\166\10\11\6\0\3\11\11\0\1\167\21\11\6\0"+
    "\3\11\11\0\16\11\1\170\3\11\6\0\3\11\11\0"+
    "\2\11\1\171\17\11\6\0\3\11\11\0\7\11\1\172"+
    "\12\11\6\0\3\11\11\0\12\11\1\173\7\11\6\0"+
    "\3\11\11\0\7\11\1\174\12\11";

  /** 
   * The transition table of the DFA
   */
  final private static int yytrans [] = yy_unpack();


  /* error codes */
  final private static int YY_UNKNOWN_ERROR = 0;
  final private static int YY_ILLEGAL_STATE = 1;
  final private static int YY_NO_MATCH = 2;
  final private static int YY_PUSHBACK_2BIG = 3;

  /* error messages for the codes above */
  final private static String YY_ERROR_MSG[] = {
    "Unkown internal scanner error",
    "Internal error: unknown state",
    "Error: could not match input",
    "Error: pushback value was too large"
  };

  /**
   * YY_ATTRIBUTE[aState] contains the attributes of state <code>aState</code>
   */
  private final static byte YY_ATTRIBUTE[] = {
     0,  9,  9,  1,  9,  1,  9,  1,  1,  9,  9,  9,  9,  9,  9,  1, 
     9,  9,  1,  1,  1,  1,  1,  1,  1,  1,  1,  0,  1,  9,  1,  1, 
     1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  0,  1,  1,  1, 
     1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  0,  1,  1,  1, 
     1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  9,  1,  1, 
     1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1, 
     1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1, 
     1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1
  };

  /** the input device */
  private java.io.Reader yy_reader;

  /** the current state of the DFA */
  private int yy_state;

  /** the current lexical state */
  private int yy_lexical_state = YYINITIAL;

  /** this buffer contains the current text to be matched and is
      the source of the yytext() string */
  private char yy_buffer[] = new char[YY_BUFFERSIZE];

  /** the textposition at the last accepting state */
  private int yy_markedPos;

  /** the textposition at the last state to be included in yytext */
  private int yy_pushbackPos;

  /** the current text position in the buffer */
  private int yy_currentPos;

  /** startRead marks the beginning of the yytext() string in the buffer */
  private int yy_startRead;

  /** endRead marks the last character in the buffer, that has been read
      from input */
  private int yy_endRead;

  /** number of newlines encountered up to the start of the matched text */
  private int yyline;

  /** the number of characters up to the start of the matched text */
  private int yychar;

  /**
   * the number of characters from the last newline up to the start of the 
   * matched text
   */
  private int yycolumn; 

  /** 
   * yy_atBOL == true <=> the scanner is currently at the beginning of a line
   */
  private boolean yy_atBOL = true;

  /** yy_atEOF == true <=> the scanner is at the EOF */
  private boolean yy_atEOF;

  /** denotes if the user-EOF-code has already been executed */
  private boolean yy_eof_done;

  /* user code: */
    /* To create a new java_cup.runtime.Symbol with information about
       the current token, the token will have no value in this
       case. */
    private Symbol symbol(int type) {
        return new Symbol(type, yyline, yycolumn);
    }
    
    /* Also creates a new java_cup.runtime.Symbol with information
       about the current token, but this object has a value. */
    private Symbol symbol(int type, Object value) {
        return new Symbol(type, yyline, yycolumn, value);
    }


  /**
   * Creates a new scanner
   * There is also a java.io.InputStream version of this constructor.
   *
   * @param   in  the java.io.Reader to read input from.
   */
  Lexer(java.io.Reader in) {
    this.yy_reader = in;
  }

  /**
   * Creates a new scanner.
   * There is also java.io.Reader version of this constructor.
   *
   * @param   in  the java.io.Inputstream to read input from.
   */
  Lexer(java.io.InputStream in) {
    this(new java.io.InputStreamReader(in));
  }

  /** 
   * Unpacks the split, compressed DFA transition table.
   *
   * @return the unpacked transition table
   */
  private static int [] yy_unpack() {
    int [] trans = new int[3276];
    int offset = 0;
    offset = yy_unpack(yy_packed0, offset, trans);
    return trans;
  }

  /** 
   * Unpacks the compressed DFA transition table.
   *
   * @param packed   the packed transition table
   * @return         the index of the last entry
   */
  private static int yy_unpack(String packed, int offset, int [] trans) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      value--;
      do trans[j++] = value; while (--count > 0);
    }
    return j;
  }


  /**
   * Refills the input buffer.
   *
   * @return      <code>false</code>, iff there was new input.
   * 
   * @exception   IOException  if any I/O-Error occurs
   */
  private boolean yy_refill() throws java.io.IOException {

    /* first: make room (if you can) */
    if (yy_startRead > 0) {
      System.arraycopy(yy_buffer, yy_startRead, 
                       yy_buffer, 0, 
                       yy_endRead-yy_startRead);

      /* translate stored positions */
      yy_endRead-= yy_startRead;
      yy_currentPos-= yy_startRead;
      yy_markedPos-= yy_startRead;
      yy_pushbackPos-= yy_startRead;
      yy_startRead = 0;
    }

    /* is the buffer big enough? */
    if (yy_currentPos >= yy_buffer.length) {
      /* if not: blow it up */
      char newBuffer[] = new char[yy_currentPos*2];
      System.arraycopy(yy_buffer, 0, newBuffer, 0, yy_buffer.length);
      yy_buffer = newBuffer;
    }

    /* finally: fill the buffer with new input */
    int numRead = yy_reader.read(yy_buffer, yy_endRead, 
                                            yy_buffer.length-yy_endRead);

    if (numRead < 0) {
      return true;
    }
    else {
      yy_endRead+= numRead;  
      return false;
    }
  }


  /**
   * Closes the input stream.
   */
  final public void yyclose() throws java.io.IOException {
    yy_atEOF = true;            /* indicate end of file */
    yy_endRead = yy_startRead;  /* invalidate buffer    */

    if (yy_reader != null)
      yy_reader.close();
  }


  /**
   * Closes the current stream, and resets the
   * scanner to read from a new input stream.
   *
   * All internal variables are reset, the old input stream 
   * <b>cannot</b> be reused (internal buffer is discarded and lost).
   * Lexical state is set to <tt>YY_INITIAL</tt>.
   *
   * @param reader   the new input stream 
   */
  final public void yyreset(java.io.Reader reader) throws java.io.IOException {
    yyclose();
    yy_reader = reader;
    yy_atBOL  = true;
    yy_atEOF  = false;
    yy_endRead = yy_startRead = 0;
    yy_currentPos = yy_markedPos = yy_pushbackPos = 0;
    yyline = yychar = yycolumn = 0;
    yy_lexical_state = YYINITIAL;
  }


  /**
   * Returns the current lexical state.
   */
  final public int yystate() {
    return yy_lexical_state;
  }


  /**
   * Enters a new lexical state
   *
   * @param newState the new lexical state
   */
  final public void yybegin(int newState) {
    yy_lexical_state = newState;
  }


  /**
   * Returns the text matched by the current regular expression.
   */
  final public String yytext() {
    return new String( yy_buffer, yy_startRead, yy_markedPos-yy_startRead );
  }


  /**
   * Returns the character at position <tt>pos</tt> from the 
   * matched text. 
   * 
   * It is equivalent to yytext().charAt(pos), but faster
   *
   * @param pos the position of the character to fetch. 
   *            A value from 0 to yylength()-1.
   *
   * @return the character at position pos
   */
  final public char yycharat(int pos) {
    return yy_buffer[yy_startRead+pos];
  }


  /**
   * Returns the length of the matched text region.
   */
  final public int yylength() {
    return yy_markedPos-yy_startRead;
  }


  /**
   * Reports an error that occured while scanning.
   *
   * In a wellformed scanner (no or only correct usage of 
   * yypushback(int) and a match-all fallback rule) this method 
   * will only be called with things that "Can't Possibly Happen".
   * If this method is called, something is seriously wrong
   * (e.g. a JFlex bug producing a faulty scanner etc.).
   *
   * Usual syntax/scanner level error handling should be done
   * in error fallback rules.
   *
   * @param   errorCode  the code of the errormessage to display
   */
  private void yy_ScanError(int errorCode) {
    String message;
    try {
      message = YY_ERROR_MSG[errorCode];
    }
    catch (ArrayIndexOutOfBoundsException e) {
      message = YY_ERROR_MSG[YY_UNKNOWN_ERROR];
    }

    throw new Error(message);
  } 


  /**
   * Pushes the specified amount of characters back into the input stream.
   *
   * They will be read again by then next call of the scanning method
   *
   * @param number  the number of characters to be read again.
   *                This number must not be greater than yylength()!
   */
  private void yypushback(int number)  {
    if ( number > yylength() )
      yy_ScanError(YY_PUSHBACK_2BIG);

    yy_markedPos -= number;
  }


  /**
   * Contains user EOF-code, which will be executed exactly once,
   * when the end of file is reached
   */
  private void yy_do_eof() throws java.io.IOException {
    if (!yy_eof_done) {
      yy_eof_done = true;
      yyclose();
    }
  }


  /**
   * Resumes scanning until the next regular expression is matched,
   * the end of input is encountered or an I/O-Error occurs.
   *
   * @return      the next token
   * @exception   IOException  if any I/O-Error occurs
   */
  public java_cup.runtime.Symbol next_token() throws java.io.IOException {
    int yy_input;
    int yy_action;

    // cached fields:
    int yy_currentPos_l;
    int yy_startRead_l;
    int yy_markedPos_l;
    int yy_endRead_l = yy_endRead;
    char [] yy_buffer_l = yy_buffer;
    char [] yycmap_l = yycmap;

    int [] yytrans_l = yytrans;
    int [] yy_rowMap_l = yy_rowMap;
    byte [] yy_attr_l = YY_ATTRIBUTE;

    while (true) {
      yy_markedPos_l = yy_markedPos;

      boolean yy_r = false;
      for (yy_currentPos_l = yy_startRead; yy_currentPos_l < yy_markedPos_l;
                                                             yy_currentPos_l++) {
        switch (yy_buffer_l[yy_currentPos_l]) {
        case '\u000B':
        case '\u000C':
        case '\u0085':
        case '\u2028':
        case '\u2029':
          yyline++;
          yycolumn = 0;
          yy_r = false;
          break;
        case '\r':
          yyline++;
          yycolumn = 0;
          yy_r = true;
          break;
        case '\n':
          if (yy_r)
            yy_r = false;
          else {
            yyline++;
            yycolumn = 0;
          }
          break;
        default:
          yy_r = false;
          yycolumn++;
        }
      }

      if (yy_r) {
        // peek one character ahead if it is \n (if we have counted one line too much)
        boolean yy_peek;
        if (yy_markedPos_l < yy_endRead_l)
          yy_peek = yy_buffer_l[yy_markedPos_l] == '\n';
        else if (yy_atEOF)
          yy_peek = false;
        else {
          boolean eof = yy_refill();
          yy_markedPos_l = yy_markedPos;
          yy_buffer_l = yy_buffer;
          if (eof) 
            yy_peek = false;
          else 
            yy_peek = yy_buffer_l[yy_markedPos_l] == '\n';
        }
        if (yy_peek) yyline--;
      }
      yy_action = -1;

      yy_startRead_l = yy_currentPos_l = yy_currentPos = 
                       yy_startRead = yy_markedPos_l;

      yy_state = yy_lexical_state;


      yy_forAction: {
        while (true) {

          if (yy_currentPos_l < yy_endRead_l)
            yy_input = yy_buffer_l[yy_currentPos_l++];
          else if (yy_atEOF) {
            yy_input = YYEOF;
            break yy_forAction;
          }
          else {
            // store back cached positions
            yy_currentPos  = yy_currentPos_l;
            yy_markedPos   = yy_markedPos_l;
            boolean eof = yy_refill();
            // get translated positions and possibly new buffer
            yy_currentPos_l  = yy_currentPos;
            yy_markedPos_l   = yy_markedPos;
            yy_buffer_l      = yy_buffer;
            yy_endRead_l     = yy_endRead;
            if (eof) {
              yy_input = YYEOF;
              break yy_forAction;
            }
            else {
              yy_input = yy_buffer_l[yy_currentPos_l++];
            }
          }
          int yy_next = yytrans_l[ yy_rowMap_l[yy_state] + yycmap_l[yy_input] ];
          if (yy_next == -1) break yy_forAction;
          yy_state = yy_next;

          int yy_attributes = yy_attr_l[yy_state];
          if ( (yy_attributes & 1) == 1 ) {
            yy_action = yy_state; 
            yy_markedPos_l = yy_currentPos_l; 
            if ( (yy_attributes & 8) == 8 ) break yy_forAction;
          }

        }
      }

      // store back cached position
      yy_markedPos = yy_markedPos_l;

      switch (yy_action) {

        case 123: 
          {   return symbol(sym.FUNCAOINI); }
        case 125: break;
        case 118: 
          {   return symbol(sym.DECFLOAT);  }
        case 126: break;
        case 117: 
          {   return symbol(sym.FUNCAOFIM); }
        case 127: break;
        case 110: 
          {   return symbol(sym.PROGRAM);   }
        case 128: break;
        case 109: 
          {   return symbol(sym.ENQUANTO);  }
        case 129: break;
        case 105: 
          {   return symbol(sym.FIMPARA);   }
        case 130: break;
        case 18: 
          {   return symbol(sym.E);         }
        case 131: break;
        case 17: 
          {   return symbol(sym.GREATER);   }
        case 132: break;
        case 16: 
          {   return symbol(sym.EQUALS);    }
        case 133: break;
        case 15: 
          {   return symbol(sym.LESS);      }
        case 134: break;
        case 14: 
          {   return symbol(sym.RPAREN);    }
        case 135: break;
        case 13: 
          {   return symbol(sym.LPAREN);    }
        case 136: break;
        case 2: 
          {   return symbol(sym.TIMES);     }
        case 137: break;
        case 3: 
          {   return symbol(sym.DIVIDE);    }
        case 138: break;
        case 9: 
          {   return symbol(sym.PLUS);      }
        case 139: break;
        case 10: 
          {   return symbol(sym.MINUS);     }
        case 140: break;
        case 29: 
          {   return symbol(sym.ATTRIB);    }
        case 141: break;
        case 32: 
          {   return symbol(sym.IFF);       }
        case 142: break;
        case 36: 
          {   return symbol(sym.OU);        }
        case 143: break;
        case 43: 
          {   return symbol(sym.DE);        }
        case 144: break;
        case 49: 
          {   return symbol(sym.ATE);       }
        case 145: break;
        case 56: 
          {   return symbol(sym.ENDPRG);    }
        case 146: break;
        case 67: 
          {   return symbol(sym.PARA);      }
        case 147: break;
        case 70: 
          {   return symbol(sym.FACA);      }
        case 148: break;
        case 76: 
          {   return symbol(sym.LEIA);      }
        case 149: break;
        case 79: 
          {   return symbol(sym.THENN);     }
        case 150: break;
        case 81: 
          {   return symbol(sym.ELSEE);     }
        case 151: break;
        case 83: 
          {   return symbol(sym.PASSO);     }
        case 152: break;
        case 87: 
          {   return symbol(sym.ENDELSE);   }
        case 153: break;
        case 94: 
          {   return symbol(sym.STARTPRG);  }
        case 154: break;
        case 98: 
          {   return symbol(sym.FUNCAO);    }
        case 155: break;
        case 100: 
          {   return symbol(sym.WRITELINE); }
        case 156: break;
        case 103: 
          {   return symbol(sym.DECLINT);   }
        case 157: break;
        case 4: 
        case 5: 
          {  /* just skip what was found, do nothing */  }
        case 158: break;
        case 6: 
        case 7: 
          {  /* System.out.print(yytext()); */
                         return symbol(sym.NUMBER, new Integer(yytext()));  }
        case 159: break;
        case 8: 
        case 19: 
        case 20: 
        case 21: 
        case 22: 
        case 23: 
        case 24: 
        case 25: 
        case 26: 
        case 30: 
        case 31: 
        case 33: 
        case 34: 
        case 35: 
        case 37: 
        case 38: 
        case 39: 
        case 40: 
        case 41: 
        case 42: 
        case 45: 
        case 46: 
        case 47: 
        case 48: 
        case 50: 
        case 51: 
        case 52: 
        case 53: 
        case 54: 
        case 55: 
        case 57: 
        case 58: 
        case 59: 
        case 61: 
        case 62: 
        case 63: 
        case 64: 
        case 65: 
        case 66: 
        case 68: 
        case 69: 
        case 71: 
        case 72: 
        case 73: 
        case 74: 
        case 75: 
        case 78: 
        case 80: 
        case 82: 
        case 84: 
        case 85: 
        case 86: 
        case 88: 
        case 89: 
        case 90: 
        case 91: 
        case 92: 
        case 93: 
        case 95: 
        case 96: 
        case 97: 
        case 99: 
        case 101: 
        case 102: 
        case 104: 
        case 106: 
        case 107: 
        case 108: 
        case 111: 
        case 112: 
        case 113: 
        case 114: 
        case 115: 
        case 116: 
        case 119: 
        case 120: 
        case 122: 
          {  /* System.out.print(yytext()); */
                         return symbol(sym.ID, yytext()); }
        case 160: break;
        case 77: 
          {  /* For this stand-alone lexer, print out comments. */
                  System.out.println("Recognized comment: " + yytext());  }
        case 161: break;
        case 121: 
          {   return symbol(sym.FIMENQUANTO);  }
        case 162: break;
        case 12: 
          {   return symbol(sym.RCOL);    }
        case 163: break;
        case 11: 
          {   return symbol(sym.LCOL);    }
        case 164: break;
        case 1: 
          {  throw new Error("Illegal character <"+yytext()+">");  }
        case 165: break;
        case 28: 
          {  System.out.println("Recognized commentline: " + yytext()); }
        case 166: break;
        default: 
          if (yy_input == YYEOF && yy_startRead == yy_currentPos) {
            yy_atEOF = true;
            yy_do_eof();
              { return new java_cup.runtime.Symbol(sym.EOF); }
          } 
          else {
            yy_ScanError(YY_NO_MATCH);
          }
      }
    }
  }


}
