/* The following code was generated by JFlex 1.3.5 on 9/23/19, 2:58 PM */

/*
  This example comes from a short article series in the Linux 
  Gazette by Richard A. Sevenich and Christopher Lopes, titled
  "Compiler Construction Tools". The article series starts at

  http://www.linuxgazette.com/issue39/sevenich.html

  Small changes and updates to newest JFlex+Cup versions 
  by Gerwin Klein
*/

/*
  Commented By: Christopher Lopes
  File Name: lcalc.flex
  To Create: > jflex lcalc.flex

  and then after the parser is created
  > javac Lexer.java
*/
   
/* --------------------------Usercode Section------------------------ */
   
import java_cup.runtime.*;
      

/**
 * This class is a scanner generated by 
 * <a href="http://www.jflex.de/">JFlex</a> 1.3.5
 * on 9/23/19, 2:58 PM from the specification file
 * <tt>file:/home/luizsetten/Downloads/CompiladorSintatico/lcalc.flex</tt>
 */
class Lexer implements java_cup.runtime.Scanner {

  /** This character denotes the end of file */
  final public static int YYEOF = -1;

  /** initial size of the lookahead buffer */
  final private static int YY_BUFFERSIZE = 16384;

  /** lexical states */
  final public static int YYINITIAL = 0;

  /** 
   * Translates characters to character classes
   */
  final private static char [] yycmap = {
     0,  0,  0,  0,  0,  0,  0,  0,  0,  5,  3,  0,  5,  4,  0,  0, 
     0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0, 
     5,  0,  0,  0,  0,  0,  0,  0, 16, 17,  1,  9,  0, 10,  0,  2, 
     6,  7,  7,  7,  7,  7,  7,  7,  7,  7,  0, 21, 18, 19, 20,  0, 
     0,  8,  8,  8,  8,  8,  8,  8,  8,  8,  8,  8,  8,  8,  8,  8, 
     8,  8,  8,  8,  8,  8,  8,  8,  8,  8,  8, 14,  0, 15,  0,  8, 
     0, 26,  8, 24, 11, 22, 32, 29,  8, 12,  8,  8, 35, 30, 31, 28, 
    27, 36, 25, 23, 34, 33, 13,  8,  8,  8,  8,  0,  0,  0,  0,  0
  };

  /** 
   * Translates a state to a row index in the transition table
   */
  final private static int yy_rowMap [] = { 
        0,    37,    37,    74,    37,   111,   148,   185,   222,    37, 
       37,   259,   296,    37,    37,    37,    37,   333,    37,    37, 
       37,   370,   407,   444,   481,   518,   555,   592,   629,   666, 
      703,   740,   777,   814,   222,   851,    37,   888,   925,   962, 
      999,  1036,  1073,  1110,   222,  1147,  1184,  1221,  1258,  1295, 
     1332,   740,   777,   222,  1369,  1406,  1443,  1480,  1517,  1554, 
     1591,   222,  1628,  1665,  1702,  1739,  1776,  1813,  1850,  1887, 
     1924,  1961,  1998,  2035,  2072,  2109,  2146,  2183,  2220,  2257, 
      222,  2294,  2331,  2368,   222,  2405,  2442,   222,    37,  2479, 
     2516,  2553,   222,  2590,   222,  2627,  2664,   222,  2701,   222, 
     2738,  2775,  2812,   222,  2849,  2886,  2923,  2960,  2997,  3034, 
     3071,  3108,  3145,   222,   222,  3182,   222,  3219,  3256,   222, 
     3293,  3330,  3367,   222,   222,  3404,  3441,  3478,  3515,  3552, 
     3589,   222,   222,  3626,  3663,   222,  3700,   222
  };

  /** 
   * The packed transition table of the DFA (part 0)
   */
  final private static String yy_packed0 = 
    "\1\2\1\3\1\4\1\5\1\6\1\5\1\7\1\10"+
    "\1\11\1\12\1\13\1\14\1\15\1\11\1\16\1\17"+
    "\1\20\1\21\1\22\1\23\1\24\1\25\1\26\1\27"+
    "\1\11\1\30\1\31\1\32\1\33\3\11\1\34\2\11"+
    "\1\35\1\11\46\0\1\36\1\37\45\0\1\5\41\0"+
    "\3\40\1\0\2\40\2\41\40\40\1\0\2\40\2\10"+
    "\35\40\6\0\3\11\2\0\3\11\10\0\17\11\6\0"+
    "\3\11\2\0\1\11\1\42\1\11\10\0\1\43\16\11"+
    "\6\0\3\11\2\0\3\11\10\0\11\11\1\44\5\11"+
    "\12\0\1\45\40\0\3\11\2\0\3\11\10\0\1\11"+
    "\1\46\7\11\1\47\5\11\6\0\3\11\2\0\3\11"+
    "\10\0\1\50\16\11\6\0\3\11\2\0\3\11\10\0"+
    "\1\51\16\11\6\0\3\11\2\0\3\11\10\0\14\11"+
    "\1\52\2\11\6\0\3\11\2\0\3\11\10\0\3\11"+
    "\1\53\1\54\12\11\6\0\3\11\2\0\3\11\10\0"+
    "\13\11\1\55\3\11\6\0\3\11\2\0\1\11\1\56"+
    "\1\11\10\0\4\11\1\57\6\11\1\60\1\11\1\61"+
    "\1\11\6\0\3\11\2\0\3\11\10\0\1\62\16\11"+
    "\1\63\1\0\43\63\3\37\2\0\40\37\6\0\2\64"+
    "\35\0\3\40\1\0\2\40\2\65\35\40\6\0\3\11"+
    "\2\0\2\11\1\66\10\0\17\11\6\0\3\11\2\0"+
    "\1\11\1\67\1\11\10\0\14\11\1\70\2\11\6\0"+
    "\3\11\2\0\3\11\10\0\2\11\1\71\14\11\6\0"+
    "\3\11\2\0\3\11\10\0\14\11\1\72\1\11\1\73"+
    "\6\0\3\11\2\0\3\11\10\0\11\11\1\74\5\11"+
    "\6\0\3\11\2\0\3\11\10\0\14\11\1\75\2\11"+
    "\6\0\3\11\2\0\3\11\10\0\1\76\16\11\6\0"+
    "\3\11\2\0\3\11\10\0\6\11\1\77\10\11\6\0"+
    "\3\11\2\0\3\11\10\0\1\11\1\100\1\11\1\101"+
    "\13\11\6\0\3\11\2\0\3\11\10\0\10\11\1\102"+
    "\6\11\6\0\3\11\2\0\3\11\10\0\2\11\1\103"+
    "\14\11\6\0\3\11\2\0\3\11\10\0\11\11\1\104"+
    "\5\11\6\0\3\11\2\0\3\11\10\0\13\11\1\105"+
    "\3\11\6\0\3\11\2\0\1\11\1\106\1\11\10\0"+
    "\17\11\1\63\1\107\1\0\42\63\6\0\3\11\2\0"+
    "\3\11\10\0\2\11\1\110\14\11\6\0\3\11\2\0"+
    "\3\11\10\0\1\111\16\11\6\0\3\11\2\0\3\11"+
    "\10\0\3\11\1\112\13\11\6\0\3\11\2\0\3\11"+
    "\10\0\4\11\1\113\12\11\6\0\3\11\2\0\3\11"+
    "\10\0\13\11\1\114\3\11\6\0\3\11\2\0\3\11"+
    "\10\0\4\11\1\115\12\11\6\0\3\11\2\0\3\11"+
    "\10\0\6\11\1\116\10\11\6\0\3\11\2\0\3\11"+
    "\10\0\7\11\1\117\7\11\6\0\3\11\2\0\3\11"+
    "\10\0\1\11\1\120\15\11\6\0\3\11\2\0\3\11"+
    "\10\0\4\11\1\121\12\11\6\0\3\11\2\0\3\11"+
    "\10\0\1\122\1\123\3\11\1\124\11\11\6\0\3\11"+
    "\2\0\3\11\10\0\4\11\1\125\12\11\6\0\3\11"+
    "\2\0\3\11\10\0\2\11\1\126\14\11\6\0\3\11"+
    "\2\0\3\11\10\0\14\11\1\127\2\11\6\0\3\11"+
    "\2\0\3\11\10\0\4\11\1\130\12\11\1\63\1\107"+
    "\1\131\42\63\6\0\3\11\2\0\1\11\1\132\1\11"+
    "\10\0\17\11\6\0\3\11\2\0\1\11\1\133\1\11"+
    "\10\0\17\11\6\0\3\11\2\0\3\11\10\0\1\134"+
    "\16\11\6\0\3\11\2\0\3\11\10\0\6\11\1\135"+
    "\10\11\6\0\3\11\2\0\3\11\10\0\4\11\1\136"+
    "\12\11\6\0\3\11\2\0\3\11\10\0\6\11\1\137"+
    "\10\11\6\0\3\11\2\0\3\11\10\0\3\11\1\140"+
    "\13\11\6\0\3\11\2\0\3\11\10\0\3\11\1\141"+
    "\13\11\6\0\3\11\2\0\3\11\10\0\6\11\1\142"+
    "\10\11\6\0\3\11\2\0\3\11\10\0\11\11\1\143"+
    "\5\11\6\0\3\11\2\0\3\11\10\0\1\144\16\11"+
    "\6\0\3\11\2\0\3\11\10\0\4\11\1\145\12\11"+
    "\6\0\3\11\2\0\3\11\10\0\4\11\1\146\12\11"+
    "\6\0\3\11\2\0\3\11\10\0\13\11\1\147\3\11"+
    "\6\0\3\11\2\0\3\11\10\0\6\11\1\150\10\11"+
    "\6\0\3\11\2\0\3\11\10\0\3\11\1\151\13\11"+
    "\6\0\3\11\2\0\2\11\1\152\10\0\17\11\6\0"+
    "\3\11\2\0\3\11\10\0\11\11\1\153\5\11\6\0"+
    "\3\11\2\0\3\11\10\0\11\11\1\154\5\11\6\0"+
    "\3\11\2\0\3\11\10\0\4\11\1\155\12\11\6\0"+
    "\3\11\2\0\3\11\10\0\16\11\1\156\6\0\3\11"+
    "\2\0\3\11\10\0\3\11\1\157\13\11\6\0\3\11"+
    "\2\0\3\11\10\0\6\11\1\160\10\11\6\0\3\11"+
    "\2\0\3\11\10\0\4\11\1\161\12\11\6\0\3\11"+
    "\2\0\3\11\10\0\6\11\1\162\10\11\6\0\3\11"+
    "\2\0\3\11\10\0\4\11\1\163\12\11\6\0\3\11"+
    "\2\0\3\11\10\0\14\11\1\164\2\11\6\0\3\11"+
    "\2\0\3\11\10\0\6\11\1\165\10\11\6\0\3\11"+
    "\2\0\3\11\10\0\10\11\1\166\6\11\6\0\3\11"+
    "\2\0\3\11\10\0\13\11\1\167\3\11\6\0\3\11"+
    "\2\0\3\11\10\0\4\11\1\170\12\11\6\0\3\11"+
    "\2\0\1\11\1\171\1\11\10\0\12\11\1\172\4\11"+
    "\6\0\3\11\2\0\3\11\10\0\11\11\1\173\5\11"+
    "\6\0\3\11\2\0\3\11\10\0\6\11\1\174\10\11"+
    "\6\0\3\11\2\0\3\11\10\0\4\11\1\175\12\11"+
    "\6\0\3\11\2\0\3\11\10\0\4\11\1\176\12\11"+
    "\6\0\3\11\2\0\3\11\10\0\11\11\1\177\5\11"+
    "\6\0\3\11\2\0\1\11\1\200\1\11\10\0\17\11"+
    "\6\0\3\11\2\0\3\11\10\0\14\11\1\201\2\11"+
    "\6\0\3\11\2\0\3\11\10\0\11\11\1\202\5\11"+
    "\6\0\3\11\2\0\1\11\1\203\1\11\10\0\17\11"+
    "\6\0\3\11\2\0\3\11\10\0\10\11\1\204\6\11"+
    "\6\0\3\11\2\0\3\11\10\0\1\205\16\11\6\0"+
    "\3\11\2\0\3\11\10\0\14\11\1\206\2\11\6\0"+
    "\3\11\2\0\3\11\10\0\2\11\1\207\14\11\6\0"+
    "\3\11\2\0\3\11\10\0\6\11\1\210\10\11\6\0"+
    "\3\11\2\0\1\11\1\211\1\11\10\0\17\11\6\0"+
    "\3\11\2\0\3\11\10\0\6\11\1\212\10\11";

  /** 
   * The transition table of the DFA
   */
  final private static int yytrans [] = yy_unpack();


  /* error codes */
  final private static int YY_UNKNOWN_ERROR = 0;
  final private static int YY_ILLEGAL_STATE = 1;
  final private static int YY_NO_MATCH = 2;
  final private static int YY_PUSHBACK_2BIG = 3;

  /* error messages for the codes above */
  final private static String YY_ERROR_MSG[] = {
    "Unkown internal scanner error",
    "Internal error: unknown state",
    "Error: could not match input",
    "Error: pushback value was too large"
  };

  /**
   * YY_ATTRIBUTE[aState] contains the attributes of state <code>aState</code>
   */
  private final static byte YY_ATTRIBUTE[] = {
     0,  9,  9,  1,  9,  1,  1,  1,  1,  9,  9,  1,  1,  9,  9,  9, 
     9,  1,  9,  9,  9,  1,  1,  1,  1,  1,  1,  1,  1,  0,  1,  0, 
     0,  1,  1,  1,  9,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1, 
     1,  1,  0,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1, 
     1,  1,  1,  1,  1,  1,  0,  1,  1,  1,  1,  1,  1,  1,  1,  1, 
     1,  1,  1,  1,  1,  1,  1,  1,  9,  1,  1,  1,  1,  1,  1,  1, 
     1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1, 
     1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1, 
     1,  1,  1,  1,  1,  1,  1,  1,  1,  1
  };

  /** the input device */
  private java.io.Reader yy_reader;

  /** the current state of the DFA */
  private int yy_state;

  /** the current lexical state */
  private int yy_lexical_state = YYINITIAL;

  /** this buffer contains the current text to be matched and is
      the source of the yytext() string */
  private char yy_buffer[] = new char[YY_BUFFERSIZE];

  /** the textposition at the last accepting state */
  private int yy_markedPos;

  /** the textposition at the last state to be included in yytext */
  private int yy_pushbackPos;

  /** the current text position in the buffer */
  private int yy_currentPos;

  /** startRead marks the beginning of the yytext() string in the buffer */
  private int yy_startRead;

  /** endRead marks the last character in the buffer, that has been read
      from input */
  private int yy_endRead;

  /** number of newlines encountered up to the start of the matched text */
  private int yyline;

  /** the number of characters up to the start of the matched text */
  private int yychar;

  /**
   * the number of characters from the last newline up to the start of the 
   * matched text
   */
  private int yycolumn; 

  /** 
   * yy_atBOL == true <=> the scanner is currently at the beginning of a line
   */
  private boolean yy_atBOL = true;

  /** yy_atEOF == true <=> the scanner is at the EOF */
  private boolean yy_atEOF;

  /** denotes if the user-EOF-code has already been executed */
  private boolean yy_eof_done;

  /* user code: */
    /* To create a new java_cup.runtime.Symbol with information about
       the current token, the token will have no value in this
       case. */
    private Symbol symbol(int type) {
        return new Symbol(type, yyline, yycolumn);
    }
    
    /* Also creates a new java_cup.runtime.Symbol with information
       about the current token, but this object has a value. */
    private Symbol symbol(int type, Object value) {
        return new Symbol(type, yyline, yycolumn, value);
    }


  /**
   * Creates a new scanner
   * There is also a java.io.InputStream version of this constructor.
   *
   * @param   in  the java.io.Reader to read input from.
   */
  Lexer(java.io.Reader in) {
    this.yy_reader = in;
  }

  /**
   * Creates a new scanner.
   * There is also java.io.Reader version of this constructor.
   *
   * @param   in  the java.io.Inputstream to read input from.
   */
  Lexer(java.io.InputStream in) {
    this(new java.io.InputStreamReader(in));
  }

  /** 
   * Unpacks the split, compressed DFA transition table.
   *
   * @return the unpacked transition table
   */
  private static int [] yy_unpack() {
    int [] trans = new int[3737];
    int offset = 0;
    offset = yy_unpack(yy_packed0, offset, trans);
    return trans;
  }

  /** 
   * Unpacks the compressed DFA transition table.
   *
   * @param packed   the packed transition table
   * @return         the index of the last entry
   */
  private static int yy_unpack(String packed, int offset, int [] trans) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      value--;
      do trans[j++] = value; while (--count > 0);
    }
    return j;
  }


  /**
   * Refills the input buffer.
   *
   * @return      <code>false</code>, iff there was new input.
   * 
   * @exception   IOException  if any I/O-Error occurs
   */
  private boolean yy_refill() throws java.io.IOException {

    /* first: make room (if you can) */
    if (yy_startRead > 0) {
      System.arraycopy(yy_buffer, yy_startRead, 
                       yy_buffer, 0, 
                       yy_endRead-yy_startRead);

      /* translate stored positions */
      yy_endRead-= yy_startRead;
      yy_currentPos-= yy_startRead;
      yy_markedPos-= yy_startRead;
      yy_pushbackPos-= yy_startRead;
      yy_startRead = 0;
    }

    /* is the buffer big enough? */
    if (yy_currentPos >= yy_buffer.length) {
      /* if not: blow it up */
      char newBuffer[] = new char[yy_currentPos*2];
      System.arraycopy(yy_buffer, 0, newBuffer, 0, yy_buffer.length);
      yy_buffer = newBuffer;
    }

    /* finally: fill the buffer with new input */
    int numRead = yy_reader.read(yy_buffer, yy_endRead, 
                                            yy_buffer.length-yy_endRead);

    if (numRead < 0) {
      return true;
    }
    else {
      yy_endRead+= numRead;  
      return false;
    }
  }


  /**
   * Closes the input stream.
   */
  final public void yyclose() throws java.io.IOException {
    yy_atEOF = true;            /* indicate end of file */
    yy_endRead = yy_startRead;  /* invalidate buffer    */

    if (yy_reader != null)
      yy_reader.close();
  }


  /**
   * Closes the current stream, and resets the
   * scanner to read from a new input stream.
   *
   * All internal variables are reset, the old input stream 
   * <b>cannot</b> be reused (internal buffer is discarded and lost).
   * Lexical state is set to <tt>YY_INITIAL</tt>.
   *
   * @param reader   the new input stream 
   */
  final public void yyreset(java.io.Reader reader) throws java.io.IOException {
    yyclose();
    yy_reader = reader;
    yy_atBOL  = true;
    yy_atEOF  = false;
    yy_endRead = yy_startRead = 0;
    yy_currentPos = yy_markedPos = yy_pushbackPos = 0;
    yyline = yychar = yycolumn = 0;
    yy_lexical_state = YYINITIAL;
  }


  /**
   * Returns the current lexical state.
   */
  final public int yystate() {
    return yy_lexical_state;
  }


  /**
   * Enters a new lexical state
   *
   * @param newState the new lexical state
   */
  final public void yybegin(int newState) {
    yy_lexical_state = newState;
  }


  /**
   * Returns the text matched by the current regular expression.
   */
  final public String yytext() {
    return new String( yy_buffer, yy_startRead, yy_markedPos-yy_startRead );
  }


  /**
   * Returns the character at position <tt>pos</tt> from the 
   * matched text. 
   * 
   * It is equivalent to yytext().charAt(pos), but faster
   *
   * @param pos the position of the character to fetch. 
   *            A value from 0 to yylength()-1.
   *
   * @return the character at position pos
   */
  final public char yycharat(int pos) {
    return yy_buffer[yy_startRead+pos];
  }


  /**
   * Returns the length of the matched text region.
   */
  final public int yylength() {
    return yy_markedPos-yy_startRead;
  }


  /**
   * Reports an error that occured while scanning.
   *
   * In a wellformed scanner (no or only correct usage of 
   * yypushback(int) and a match-all fallback rule) this method 
   * will only be called with things that "Can't Possibly Happen".
   * If this method is called, something is seriously wrong
   * (e.g. a JFlex bug producing a faulty scanner etc.).
   *
   * Usual syntax/scanner level error handling should be done
   * in error fallback rules.
   *
   * @param   errorCode  the code of the errormessage to display
   */
  private void yy_ScanError(int errorCode) {
    String message;
    try {
      message = YY_ERROR_MSG[errorCode];
    }
    catch (ArrayIndexOutOfBoundsException e) {
      message = YY_ERROR_MSG[YY_UNKNOWN_ERROR];
    }

    throw new Error(message);
  } 


  /**
   * Pushes the specified amount of characters back into the input stream.
   *
   * They will be read again by then next call of the scanning method
   *
   * @param number  the number of characters to be read again.
   *                This number must not be greater than yylength()!
   */
  private void yypushback(int number)  {
    if ( number > yylength() )
      yy_ScanError(YY_PUSHBACK_2BIG);

    yy_markedPos -= number;
  }


  /**
   * Contains user EOF-code, which will be executed exactly once,
   * when the end of file is reached
   */
  private void yy_do_eof() throws java.io.IOException {
    if (!yy_eof_done) {
      yy_eof_done = true;
      yyclose();
    }
  }


  /**
   * Resumes scanning until the next regular expression is matched,
   * the end of input is encountered or an I/O-Error occurs.
   *
   * @return      the next token
   * @exception   IOException  if any I/O-Error occurs
   */
  public java_cup.runtime.Symbol next_token() throws java.io.IOException {
    int yy_input;
    int yy_action;

    // cached fields:
    int yy_currentPos_l;
    int yy_startRead_l;
    int yy_markedPos_l;
    int yy_endRead_l = yy_endRead;
    char [] yy_buffer_l = yy_buffer;
    char [] yycmap_l = yycmap;

    int [] yytrans_l = yytrans;
    int [] yy_rowMap_l = yy_rowMap;
    byte [] yy_attr_l = YY_ATTRIBUTE;

    while (true) {
      yy_markedPos_l = yy_markedPos;

      boolean yy_r = false;
      for (yy_currentPos_l = yy_startRead; yy_currentPos_l < yy_markedPos_l;
                                                             yy_currentPos_l++) {
        switch (yy_buffer_l[yy_currentPos_l]) {
        case '\u000B':
        case '\u000C':
        case '\u0085':
        case '\u2028':
        case '\u2029':
          yyline++;
          yycolumn = 0;
          yy_r = false;
          break;
        case '\r':
          yyline++;
          yycolumn = 0;
          yy_r = true;
          break;
        case '\n':
          if (yy_r)
            yy_r = false;
          else {
            yyline++;
            yycolumn = 0;
          }
          break;
        default:
          yy_r = false;
          yycolumn++;
        }
      }

      if (yy_r) {
        // peek one character ahead if it is \n (if we have counted one line too much)
        boolean yy_peek;
        if (yy_markedPos_l < yy_endRead_l)
          yy_peek = yy_buffer_l[yy_markedPos_l] == '\n';
        else if (yy_atEOF)
          yy_peek = false;
        else {
          boolean eof = yy_refill();
          yy_markedPos_l = yy_markedPos;
          yy_buffer_l = yy_buffer;
          if (eof) 
            yy_peek = false;
          else 
            yy_peek = yy_buffer_l[yy_markedPos_l] == '\n';
        }
        if (yy_peek) yyline--;
      }
      yy_action = -1;

      yy_startRead_l = yy_currentPos_l = yy_currentPos = 
                       yy_startRead = yy_markedPos_l;

      yy_state = yy_lexical_state;


      yy_forAction: {
        while (true) {

          if (yy_currentPos_l < yy_endRead_l)
            yy_input = yy_buffer_l[yy_currentPos_l++];
          else if (yy_atEOF) {
            yy_input = YYEOF;
            break yy_forAction;
          }
          else {
            // store back cached positions
            yy_currentPos  = yy_currentPos_l;
            yy_markedPos   = yy_markedPos_l;
            boolean eof = yy_refill();
            // get translated positions and possibly new buffer
            yy_currentPos_l  = yy_currentPos;
            yy_markedPos_l   = yy_markedPos;
            yy_buffer_l      = yy_buffer;
            yy_endRead_l     = yy_endRead;
            if (eof) {
              yy_input = YYEOF;
              break yy_forAction;
            }
            else {
              yy_input = yy_buffer_l[yy_currentPos_l++];
            }
          }
          int yy_next = yytrans_l[ yy_rowMap_l[yy_state] + yycmap_l[yy_input] ];
          if (yy_next == -1) break yy_forAction;
          yy_state = yy_next;

          int yy_attributes = yy_attr_l[yy_state];
          if ( (yy_attributes & 1) == 1 ) {
            yy_action = yy_state; 
            yy_markedPos_l = yy_currentPos_l; 
            if ( (yy_attributes & 8) == 8 ) break yy_forAction;
          }

        }
      }

      // store back cached position
      yy_markedPos = yy_markedPos_l;

      switch (yy_action) {

        case 137: 
          {   return symbol(sym.FUNCAOINI); }
        case 139: break;
        case 132: 
          {   return symbol(sym.DECFLOAT);  }
        case 140: break;
        case 131: 
          {   return symbol(sym.FUNCAOFIM); }
        case 141: break;
        case 124: 
          {   return symbol(sym.PROGRAM);   }
        case 142: break;
        case 123: 
          {   return symbol(sym.ENQUANTO);  }
        case 143: break;
        case 119: 
          {   return symbol(sym.FIMPARA);   }
        case 144: break;
        case 114: 
          {   return symbol(sym.WRITELINE); }
        case 145: break;
        case 113: 
          {   return symbol(sym.DECLINT);   }
        case 146: break;
        case 20: 
          {   return symbol(sym.SEMI);      }
        case 147: break;
        case 19: 
          {   return symbol(sym.GREATER);   }
        case 148: break;
        case 18: 
          {   return symbol(sym.EQUALS);    }
        case 149: break;
        case 17: 
          {   return symbol(sym.LESS);      }
        case 150: break;
        case 16: 
          {   return symbol(sym.RPAREN);    }
        case 151: break;
        case 15: 
          {   return symbol(sym.LPAREN);    }
        case 152: break;
        case 14: 
          {   return symbol(sym.RCOL);      }
        case 153: break;
        case 2: 
          {   return symbol(sym.TIMES);     }
        case 154: break;
        case 9: 
          {   return symbol(sym.PLUS);      }
        case 155: break;
        case 10: 
          {   return symbol(sym.MINUS);     }
        case 156: break;
        case 13: 
          {   return symbol(sym.LCOL);      }
        case 157: break;
        case 34: 
          {   return symbol(sym.DE);        }
        case 158: break;
        case 36: 
          {   return symbol(sym.ATTRIB);    }
        case 159: break;
        case 39: 
          {   return symbol(sym.IFF);       }
        case 160: break;
        case 53: 
          {   return symbol(sym.DIVIDE);    }
        case 161: break;
        case 61: 
          {   return symbol(sym.ATE);       }
        case 162: break;
        case 65: 
          {   return symbol(sym.ENDPRG);    }
        case 163: break;
        case 80: 
          {   return symbol(sym.PARA);      }
        case 164: break;
        case 84: 
          {   return symbol(sym.FACA);      }
        case 165: break;
        case 87: 
          {   return symbol(sym.LEIA);      }
        case 166: break;
        case 92: 
          {   return symbol(sym.THENN);     }
        case 167: break;
        case 94: 
          {   return symbol(sym.ELSEE);     }
        case 168: break;
        case 97: 
          {   return symbol(sym.PASSO);     }
        case 169: break;
        case 99: 
          {   return symbol(sym.ENDELSE);   }
        case 170: break;
        case 103: 
          {   return symbol(sym.STARTPRG);  }
        case 171: break;
        case 111: 
          {   return symbol(sym.FUNCAO);    }
        case 172: break;
        case 4: 
        case 5: 
          {  /* just skip what was found, do nothing */  }
        case 173: break;
        case 6: 
        case 7: 
          {  /* System.out.print(yytext()); */
                         return symbol(sym.NUMBER, new Integer(yytext()));  }
        case 174: break;
        case 8: 
        case 11: 
        case 12: 
        case 22: 
        case 23: 
        case 24: 
        case 25: 
        case 26: 
        case 27: 
        case 28: 
        case 33: 
        case 35: 
        case 37: 
        case 38: 
        case 40: 
        case 41: 
        case 42: 
        case 43: 
        case 45: 
        case 46: 
        case 47: 
        case 48: 
        case 49: 
        case 54: 
        case 55: 
        case 56: 
        case 57: 
        case 58: 
        case 59: 
        case 60: 
        case 62: 
        case 63: 
        case 64: 
        case 66: 
        case 67: 
        case 68: 
        case 69: 
        case 71: 
        case 72: 
        case 73: 
        case 74: 
        case 75: 
        case 76: 
        case 77: 
        case 78: 
        case 79: 
        case 81: 
        case 82: 
        case 83: 
        case 85: 
        case 86: 
        case 89: 
        case 90: 
        case 91: 
        case 93: 
        case 95: 
        case 96: 
        case 98: 
        case 100: 
        case 101: 
        case 102: 
        case 104: 
        case 105: 
        case 106: 
        case 107: 
        case 108: 
        case 109: 
        case 110: 
        case 112: 
        case 115: 
        case 117: 
        case 118: 
        case 120: 
        case 121: 
        case 122: 
        case 125: 
        case 126: 
        case 127: 
        case 128: 
        case 129: 
        case 130: 
        case 133: 
        case 134: 
        case 136: 
          {  /* System.out.print(yytext()); */
                         return symbol(sym.ID, yytext()); }
        case 175: break;
        case 51: 
        case 52: 
          {  /* System.out.print(yytext()); */
                         return symbol(sym.FLOAT, new Float(yytext()));  }
        case 176: break;
        case 88: 
          {  /* For this stand-alone lexer, print out comments. */
                  System.out.println("Recognized comment: " + yytext());  }
        case 177: break;
        case 135: 
          {   return symbol(sym.FIMENQUANTO);  }
        case 178: break;
        case 21: 
          {   return symbol(sym.EE);         }
        case 179: break;
        case 44: 
          {   return symbol(sym.OUU);        }
        case 180: break;
        case 116: 
          {   return symbol(sym.RETORNO);        }
        case 181: break;
        case 1: 
        case 3: 
          {  throw new Error("Illegal character <"+yytext()+">");  }
        case 182: break;
        case 30: 
          {  System.out.println("Recognized commentline: " + yytext()); }
        case 183: break;
        default: 
          if (yy_input == YYEOF && yy_startRead == yy_currentPos) {
            yy_atEOF = true;
            yy_do_eof();
              { return new java_cup.runtime.Symbol(sym.EOF); }
          } 
          else {
            yy_ScanError(YY_NO_MATCH);
          }
      }
    }
  }


}
