
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20141204 (SVN rev 60)
//----------------------------------------------------

import java_cup.runtime.*;
import java.util.*;
import java.util.Stack;
import java_cup.runtime.XMLElement;

/** CUP v0.11b 20141204 (SVN rev 60) generated parser.
  */
@SuppressWarnings({"rawtypes"})
public class parser extends java_cup.runtime.lr_parser {

 public final Class getSymbolContainer() {
    return sym.class;
}

  /** Default constructor. */
  public parser() {super();}

  /** Constructor which sets the default scanner. */
  public parser(java_cup.runtime.Scanner s) {super(s);}

  /** Constructor which sets the default scanner. */
  public parser(java_cup.runtime.Scanner s, java_cup.runtime.SymbolFactory sf) {super(s,sf);}

  /** Production table. */
  protected static final short _production_table[][] = 
    unpackFromStrings(new String[] {
    "\000\075\000\002\002\007\000\002\002\004\000\002\010" +
    "\004\000\002\010\003\000\002\015\005\000\002\025\004" +
    "\000\002\025\003\000\002\024\006\000\002\011\003\000" +
    "\002\011\003\000\002\011\003\000\002\011\003\000\002" +
    "\011\003\000\002\011\003\000\002\011\003\000\002\011" +
    "\003\000\002\011\003\000\002\020\005\000\002\022\011" +
    "\000\002\021\004\000\002\021\005\000\002\021\005\000" +
    "\002\014\006\000\002\014\006\000\002\014\005\000\002" +
    "\014\005\000\002\013\004\000\002\013\003\000\002\012" +
    "\003\000\002\030\005\000\002\030\005\000\002\030\005" +
    "\000\002\030\005\000\002\030\005\000\002\030\005\000" +
    "\002\030\005\000\002\030\005\000\002\030\005\000\002" +
    "\030\005\000\002\030\003\000\002\030\003\000\002\030" +
    "\003\000\002\006\007\000\002\007\004\000\002\007\004" +
    "\000\002\007\004\000\002\007\002\000\002\023\007\000" +
    "\002\027\015\000\002\031\003\000\002\031\003\000\002" +
    "\003\004\000\002\003\003\000\002\003\002\000\002\026" +
    "\013\000\002\026\012\000\002\004\005\000\002\017\004" +
    "\000\002\016\004\000\002\016\003\000\002\016\002" });

  /** Access to production table. */
  public short[][] production_table() {return _production_table;}

  /** Parse-action table. */
  protected static final short[][] _action_table = 
    unpackFromStrings(new String[] {
    "\000\205\000\006\016\uffcc\044\007\001\002\000\004\002" +
    "\207\001\002\000\006\016\uffcd\044\uffcd\001\002\000\006" +
    "\016\203\044\007\001\002\000\010\022\011\023\012\052" +
    "\010\001\002\000\004\011\174\001\002\000\004\052\uffcf" +
    "\001\002\000\004\052\uffd0\001\002\000\004\052\014\001" +
    "\002\000\004\011\015\001\002\000\010\012\uffc5\022\011" +
    "\023\012\001\002\000\004\052\173\001\002\000\010\012" +
    "\021\022\011\023\012\001\002\000\010\012\uffc6\022\uffc6" +
    "\023\uffc6\001\002\000\004\045\023\001\002\000\010\012" +
    "\uffc7\022\uffc7\023\uffc7\001\002\000\024\005\030\021\036" +
    "\022\011\023\012\026\042\036\032\041\047\043\046\052" +
    "\031\001\002\000\004\035\166\001\002\000\004\052\157" +
    "\001\002\000\040\005\ufffe\020\ufffe\021\ufffe\022\ufffe\023" +
    "\ufffe\026\ufffe\033\ufffe\034\ufffe\036\ufffe\041\ufffe\042\ufffe" +
    "\043\ufffe\046\ufffe\051\ufffe\052\ufffe\001\002\000\040\005" +
    "\ufff2\020\ufff2\021\ufff2\022\ufff2\023\ufff2\026\ufff2\033\ufff2" +
    "\034\ufff2\036\ufff2\041\ufff2\042\ufff2\043\ufff2\046\ufff2\051" +
    "\ufff2\052\ufff2\001\002\000\012\011\055\052\052\053\054" +
    "\054\057\001\002\000\010\011\137\025\135\035\136\001" +
    "\002\000\004\052\123\001\002\000\040\005\ufff1\020\ufff1" +
    "\021\ufff1\022\ufff1\023\ufff1\026\ufff1\033\ufff1\034\ufff1\036" +
    "\ufff1\041\ufff1\042\ufff1\043\ufff1\046\ufff1\051\ufff1\052\ufff1" +
    "\001\002\000\040\005\ufff4\020\ufff4\021\ufff4\022\ufff4\023" +
    "\ufff4\026\ufff4\033\ufff4\034\ufff4\036\ufff4\041\ufff4\042\ufff4" +
    "\043\ufff4\046\ufff4\051\ufff4\052\ufff4\001\002\000\040\005" +
    "\ufff9\020\ufff9\021\ufff9\022\ufff9\023\ufff9\026\ufff9\033\ufff9" +
    "\034\ufff9\036\ufff9\041\ufff9\042\ufff9\043\ufff9\046\ufff9\051" +
    "\ufff9\052\ufff9\001\002\000\012\011\055\052\052\053\054" +
    "\054\057\001\002\000\040\005\ufff6\020\ufff6\021\ufff6\022" +
    "\ufff6\023\ufff6\026\ufff6\033\ufff6\034\ufff6\036\ufff6\041\ufff6" +
    "\042\ufff6\043\ufff6\046\ufff6\051\ufff6\052\ufff6\001\002\000" +
    "\026\005\030\021\036\022\011\023\012\026\042\036\032" +
    "\041\047\043\046\046\120\052\031\001\002\000\040\005" +
    "\ufff8\020\ufff8\021\ufff8\022\ufff8\023\ufff8\026\ufff8\033\ufff8" +
    "\034\ufff8\036\ufff8\041\ufff8\042\ufff8\043\ufff8\046\ufff8\051" +
    "\ufff8\052\ufff8\001\002\000\012\011\055\052\052\053\054" +
    "\054\057\001\002\000\040\005\ufff3\020\ufff3\021\ufff3\022" +
    "\ufff3\023\ufff3\026\ufff3\033\ufff3\034\ufff3\036\ufff3\041\ufff3" +
    "\042\ufff3\043\ufff3\046\ufff3\051\ufff3\052\ufff3\001\002\000" +
    "\040\005\ufff5\020\ufff5\021\ufff5\022\ufff5\023\ufff5\026\ufff5" +
    "\033\ufff5\034\ufff5\036\ufff5\041\ufff5\042\ufff5\043\ufff5\046" +
    "\ufff5\051\ufff5\052\ufff5\001\002\000\040\005\ufff7\020\ufff7" +
    "\021\ufff7\022\ufff7\023\ufff7\026\ufff7\033\ufff7\034\ufff7\036" +
    "\ufff7\041\ufff7\042\ufff7\043\ufff7\046\ufff7\051\ufff7\052\ufff7" +
    "\001\002\000\012\011\055\052\052\053\054\054\057\001" +
    "\002\000\004\052\050\001\002\000\004\031\051\001\002" +
    "\000\040\005\ufffd\020\ufffd\021\ufffd\022\ufffd\023\ufffd\026" +
    "\ufffd\033\ufffd\034\ufffd\036\ufffd\041\ufffd\042\ufffd\043\ufffd" +
    "\046\ufffd\051\ufffd\052\ufffd\001\002\000\044\004\uffda\006" +
    "\uffda\007\uffda\010\uffda\011\uffda\012\uffda\013\uffda\014\uffda" +
    "\015\uffda\027\uffda\030\uffda\031\uffda\032\uffda\050\uffda\052" +
    "\uffda\053\uffda\054\uffda\001\002\000\004\050\104\001\002" +
    "\000\044\004\uffd9\006\uffd9\007\uffd9\010\uffd9\011\uffd9\012" +
    "\uffd9\013\uffd9\014\uffd9\015\uffd9\027\uffd9\030\uffd9\031\uffd9" +
    "\032\uffd9\050\uffd9\052\uffd9\053\uffd9\054\uffd9\001\002\000" +
    "\012\011\055\052\052\053\054\054\057\001\002\000\042" +
    "\004\063\006\060\007\065\010\061\011\uffe5\013\066\014" +
    "\062\015\064\027\070\030\067\031\uffe5\032\uffe5\050\uffe5" +
    "\052\uffe5\053\uffe5\054\uffe5\001\002\000\044\004\uffd8\006" +
    "\uffd8\007\uffd8\010\uffd8\011\uffd8\012\uffd8\013\uffd8\014\uffd8" +
    "\015\uffd8\027\uffd8\030\uffd8\031\uffd8\032\uffd8\050\uffd8\052" +
    "\uffd8\053\uffd8\054\uffd8\001\002\000\012\011\055\052\052" +
    "\053\054\054\057\001\002\000\012\011\055\052\052\053" +
    "\054\054\057\001\002\000\012\011\055\052\052\053\054" +
    "\054\057\001\002\000\012\011\055\052\052\053\054\054" +
    "\057\001\002\000\012\011\055\052\052\053\054\054\057" +
    "\001\002\000\012\011\055\052\052\053\054\054\057\001" +
    "\002\000\012\011\055\052\052\053\054\054\057\001\002" +
    "\000\012\011\055\052\052\053\054\054\057\001\002\000" +
    "\012\011\055\052\052\053\054\054\057\001\002\000\044" +
    "\004\uffdd\006\uffdd\007\uffdd\010\uffdd\011\uffdd\012\uffdd\013" +
    "\uffdd\014\uffdd\015\uffdd\027\uffdd\030\uffdd\031\uffdd\032\uffdd" +
    "\050\uffdd\052\uffdd\053\uffdd\054\uffdd\001\002\000\044\004" +
    "\uffdc\006\uffdc\007\uffdc\010\uffdc\011\uffdc\012\uffdc\013\uffdc" +
    "\014\uffdc\015\uffdc\027\uffdc\030\uffdc\031\uffdc\032\uffdc\050" +
    "\uffdc\052\uffdc\053\uffdc\054\uffdc\001\002\000\044\004\063" +
    "\006\060\007\065\010\061\011\uffdf\012\uffdf\013\uffdf\014" +
    "\062\015\064\027\070\030\067\031\uffdf\032\uffdf\050\uffdf" +
    "\052\uffdf\053\uffdf\054\uffdf\001\002\000\044\004\uffe2\006" +
    "\uffe2\007\uffe2\010\uffe2\011\uffe2\012\uffe2\013\uffe2\014\uffe2" +
    "\015\uffe2\027\070\030\067\031\uffe2\032\uffe2\050\uffe2\052" +
    "\uffe2\053\uffe2\054\uffe2\001\002\000\044\004\063\006\060" +
    "\007\065\010\061\011\uffde\012\uffde\013\uffde\014\uffde\015" +
    "\uffde\027\070\030\067\031\uffde\032\uffde\050\uffde\052\uffde" +
    "\053\uffde\054\uffde\001\002\000\044\004\uffe4\006\uffe4\007" +
    "\065\010\061\011\uffe4\012\uffe4\013\uffe4\014\uffe4\015\uffe4" +
    "\027\070\030\067\031\uffe4\032\uffe4\050\uffe4\052\uffe4\053" +
    "\uffe4\054\uffe4\001\002\000\044\004\063\006\060\007\065" +
    "\010\061\011\uffe0\012\uffe0\013\uffe0\014\uffe0\015\uffe0\027" +
    "\070\030\067\031\uffe0\032\uffe0\050\uffe0\052\uffe0\053\uffe0" +
    "\054\uffe0\001\002\000\044\004\uffe1\006\uffe1\007\uffe1\010" +
    "\uffe1\011\uffe1\012\uffe1\013\uffe1\014\uffe1\015\uffe1\027\070" +
    "\030\067\031\uffe1\032\uffe1\050\uffe1\052\uffe1\053\uffe1\054" +
    "\uffe1\001\002\000\044\004\uffe3\006\uffe3\007\065\010\061" +
    "\011\uffe3\012\uffe3\013\uffe3\014\uffe3\015\uffe3\027\070\030" +
    "\067\031\uffe3\032\uffe3\050\uffe3\052\uffe3\053\uffe3\054\uffe3" +
    "\001\002\000\026\004\063\006\060\007\065\010\061\012" +
    "\103\013\066\014\062\015\064\027\070\030\067\001\002" +
    "\000\044\004\uffdb\006\uffdb\007\uffdb\010\uffdb\011\uffdb\012" +
    "\uffdb\013\uffdb\014\uffdb\015\uffdb\027\uffdb\030\uffdb\031\uffdb" +
    "\032\uffdb\050\uffdb\052\uffdb\053\uffdb\054\uffdb\001\002\000" +
    "\024\005\030\021\036\022\011\023\012\026\042\036\032" +
    "\041\047\043\046\052\031\001\002\000\026\005\030\021" +
    "\036\022\011\023\012\026\042\036\032\041\047\043\046" +
    "\051\106\052\031\001\002\000\040\005\uffd2\020\uffd2\021" +
    "\uffd2\022\uffd2\023\uffd2\026\uffd2\033\uffd2\034\uffd2\036\uffd2" +
    "\041\uffd2\042\uffd2\043\uffd2\046\uffd2\051\uffd2\052\uffd2\001" +
    "\002\000\040\005\uffff\020\uffff\021\uffff\022\uffff\023\uffff" +
    "\026\uffff\033\uffff\034\uffff\036\uffff\041\uffff\042\uffff\043" +
    "\uffff\046\uffff\051\uffff\052\uffff\001\002\000\016\011\uffe6" +
    "\031\uffe6\032\uffe6\052\uffe6\053\uffe6\054\uffe6\001\002\000" +
    "\014\011\055\032\112\052\052\053\054\054\057\001\002" +
    "\000\024\005\030\021\036\022\011\023\012\026\042\036" +
    "\032\041\047\043\046\052\031\001\002\000\016\011\uffe7" +
    "\031\uffe7\032\uffe7\052\uffe7\053\uffe7\054\uffe7\001\002\000" +
    "\026\005\030\021\036\022\011\023\012\026\042\033\115" +
    "\036\032\041\047\043\046\052\031\001\002\000\024\005" +
    "\030\021\036\022\011\023\012\026\042\036\032\041\047" +
    "\043\046\052\031\001\002\000\026\005\030\021\036\022" +
    "\011\023\012\026\042\034\117\036\032\041\047\043\046" +
    "\052\031\001\002\000\040\005\uffef\020\uffef\021\uffef\022" +
    "\uffef\023\uffef\026\uffef\033\uffef\034\uffef\036\uffef\041\uffef" +
    "\042\uffef\043\uffef\046\uffef\051\uffef\052\uffef\001\002\000" +
    "\006\016\uffcb\044\uffcb\001\002\000\004\031\122\001\002" +
    "\000\040\005\ufff0\020\ufff0\021\ufff0\022\ufff0\023\ufff0\026" +
    "\ufff0\033\ufff0\034\ufff0\036\ufff0\041\ufff0\042\ufff0\043\ufff0" +
    "\046\ufff0\051\ufff0\052\ufff0\001\002\000\004\037\124\001" +
    "\002\000\004\053\125\001\002\000\004\040\126\001\002" +
    "\000\004\053\127\001\002\000\004\047\130\001\002\000" +
    "\004\053\131\001\002\000\004\050\132\001\002\000\024" +
    "\005\030\021\036\022\011\023\012\026\042\036\032\041" +
    "\047\043\046\052\031\001\002\000\026\005\030\021\036" +
    "\022\011\023\012\026\042\036\032\041\047\042\134\043" +
    "\046\052\031\001\002\000\040\005\uffd1\020\uffd1\021\uffd1" +
    "\022\uffd1\023\uffd1\026\uffd1\033\uffd1\034\uffd1\036\uffd1\041" +
    "\uffd1\042\uffd1\043\uffd1\046\uffd1\051\uffd1\052\uffd1\001\002" +
    "\000\004\053\153\001\002\000\012\011\055\052\150\053" +
    "\054\054\057\001\002\000\014\011\uffd3\012\uffd3\052\uffd3" +
    "\053\uffd3\054\uffd3\001\002\000\014\011\055\012\144\052" +
    "\141\053\054\054\057\001\002\000\040\004\uffda\006\uffda" +
    "\007\uffda\010\uffda\011\137\012\uffda\013\uffda\014\uffda\015" +
    "\uffda\025\135\027\uffda\030\uffda\052\uffda\053\uffda\054\uffda" +
    "\001\002\000\014\011\uffd4\012\uffd4\052\uffd4\053\uffd4\054" +
    "\uffd4\001\002\000\014\011\uffd5\012\uffd5\052\uffd5\053\uffd5" +
    "\054\uffd5\001\002\000\004\031\146\001\002\000\036\004" +
    "\063\006\060\007\065\010\061\011\uffd6\012\uffd6\013\066" +
    "\014\062\015\064\027\070\030\067\052\uffd6\053\uffd6\054" +
    "\uffd6\001\002\000\050\005\uffd7\011\uffd7\012\uffd7\020\uffd7" +
    "\021\uffd7\022\uffd7\023\uffd7\026\uffd7\033\uffd7\034\uffd7\036" +
    "\uffd7\041\uffd7\042\uffd7\043\uffd7\046\uffd7\051\uffd7\052\uffd7" +
    "\053\uffd7\054\uffd7\001\002\000\040\005\uffe9\020\uffe9\021" +
    "\uffe9\022\uffe9\023\uffe9\026\uffe9\033\uffe9\034\uffe9\036\uffe9" +
    "\041\uffe9\042\uffe9\043\uffe9\046\uffe9\051\uffe9\052\uffe9\001" +
    "\002\000\030\004\uffda\006\uffda\007\uffda\010\uffda\011\137" +
    "\013\uffda\014\uffda\015\uffda\027\uffda\030\uffda\031\uffda\001" +
    "\002\000\026\004\063\006\060\007\065\010\061\013\066" +
    "\014\062\015\064\027\070\030\067\031\152\001\002\000" +
    "\040\005\uffeb\020\uffeb\021\uffeb\022\uffeb\023\uffeb\026\uffeb" +
    "\033\uffeb\034\uffeb\036\uffeb\041\uffeb\042\uffeb\043\uffeb\046" +
    "\uffeb\051\uffeb\052\uffeb\001\002\000\004\024\154\001\002" +
    "\000\020\011\ufffa\012\ufffa\031\ufffa\035\ufffa\052\ufffa\053" +
    "\ufffa\054\ufffa\001\002\000\014\011\055\031\156\052\052" +
    "\053\054\054\057\001\002\000\040\005\uffc9\020\uffc9\021" +
    "\uffc9\022\uffc9\023\uffc9\026\uffc9\033\uffc9\034\uffc9\036\uffc9" +
    "\041\uffc9\042\uffc9\043\uffc9\046\uffc9\051\uffc9\052\uffc9\001" +
    "\002\000\010\025\135\031\172\035\136\001\002\000\010" +
    "\031\ufffb\035\166\052\ufffb\001\002\000\040\005\uffee\020" +
    "\uffee\021\uffee\022\uffee\023\uffee\026\uffee\033\uffee\034\uffee" +
    "\036\uffee\041\uffee\042\uffee\043\uffee\046\uffee\051\uffee\052" +
    "\uffee\001\002\000\006\031\165\052\163\001\002\000\004" +
    "\025\135\001\002\000\006\031\ufffc\052\ufffc\001\002\000" +
    "\040\005\uffed\020\uffed\021\uffed\022\uffed\023\uffed\026\uffed" +
    "\033\uffed\034\uffed\036\uffed\041\uffed\042\uffed\043\uffed\046" +
    "\uffed\051\uffed\052\uffed\001\002\000\012\011\055\052\150" +
    "\053\054\054\057\001\002\000\040\005\uffe8\020\uffe8\021" +
    "\uffe8\022\uffe8\023\uffe8\026\uffe8\033\uffe8\034\uffe8\036\uffe8" +
    "\041\uffe8\042\uffe8\043\uffe8\046\uffe8\051\uffe8\052\uffe8\001" +
    "\002\000\026\004\063\006\060\007\065\010\061\013\066" +
    "\014\062\015\064\027\070\030\067\031\171\001\002\000" +
    "\040\005\uffea\020\uffea\021\uffea\022\uffea\023\uffea\026\uffea" +
    "\033\uffea\034\uffea\036\uffea\041\uffea\042\uffea\043\uffea\046" +
    "\uffea\051\uffea\052\uffea\001\002\000\040\005\uffec\020\uffec" +
    "\021\uffec\022\uffec\023\uffec\026\uffec\033\uffec\034\uffec\036" +
    "\uffec\041\uffec\042\uffec\043\uffec\046\uffec\051\uffec\052\uffec" +
    "\001\002\000\010\012\uffc8\022\uffc8\023\uffc8\001\002\000" +
    "\010\012\uffc5\022\011\023\012\001\002\000\010\012\176" +
    "\022\011\023\012\001\002\000\004\045\177\001\002\000" +
    "\024\005\030\021\036\022\011\023\012\026\042\036\032" +
    "\041\047\043\046\052\031\001\002\000\026\005\030\021" +
    "\036\022\011\023\012\026\042\036\032\041\047\043\046" +
    "\046\201\052\031\001\002\000\006\016\uffca\044\uffca\001" +
    "\002\000\006\016\uffce\044\uffce\001\002\000\004\017\204" +
    "\001\002\000\024\005\030\021\036\022\011\023\012\026" +
    "\042\036\032\041\047\043\046\052\031\001\002\000\026" +
    "\005\030\020\206\021\036\022\011\023\012\026\042\036" +
    "\032\041\047\043\046\052\031\001\002\000\004\002\001" +
    "\001\002\000\004\002\000\001\002" });

  /** Access to parse-action table. */
  public short[][] action_table() {return _action_table;}

  /** <code>reduce_goto</code> table. */
  protected static final short[][] _reduce_table = 
    unpackFromStrings(new String[] {
    "\000\205\000\010\002\003\003\005\026\004\001\001\000" +
    "\002\001\001\000\002\001\001\000\004\026\201\001\001" +
    "\000\004\031\012\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\010\016\016\017\017\031\015\001\001\000\002\001" +
    "\001\000\006\017\021\031\015\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\034\004\032\006" +
    "\026\010\037\011\025\014\040\015\042\020\044\021\034" +
    "\022\036\023\043\024\023\027\033\031\024\001\001\000" +
    "\002\001\001\000\010\014\160\024\157\025\161\001\001" +
    "\000\002\001\001\000\002\001\001\000\010\012\107\013" +
    "\154\030\055\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\006\012\120\030\055\001\001\000\002\001\001\000\032" +
    "\004\032\006\026\011\106\014\040\015\042\020\044\021" +
    "\034\022\036\023\043\024\023\027\033\031\024\001\001" +
    "\000\002\001\001\000\010\012\107\013\110\030\055\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\006\012\052\030\055\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\004\030\101\001\001\000" +
    "\002\001\001\000\002\001\001\000\004\030\100\001\001" +
    "\000\004\030\077\001\001\000\004\030\076\001\001\000" +
    "\004\030\075\001\001\000\004\030\074\001\001\000\004" +
    "\030\073\001\001\000\004\030\072\001\001\000\004\030" +
    "\071\001\001\000\004\030\070\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\034\004\032\006\026\010\104\011\025\014\040" +
    "\015\042\020\044\021\034\022\036\023\043\024\023\027" +
    "\033\031\024\001\001\000\032\004\032\006\026\011\106" +
    "\014\040\015\042\020\044\021\034\022\036\023\043\024" +
    "\023\027\033\031\024\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\006\012\112\030\055\001" +
    "\001\000\034\004\032\006\026\010\113\011\025\014\040" +
    "\015\042\020\044\021\034\022\036\023\043\024\023\027" +
    "\033\031\024\001\001\000\002\001\001\000\032\004\032" +
    "\006\026\011\106\014\040\015\042\020\044\021\034\022" +
    "\036\023\043\024\023\027\033\031\024\001\001\000\034" +
    "\004\032\006\026\010\115\011\025\014\040\015\042\020" +
    "\044\021\034\022\036\023\043\024\023\027\033\031\024" +
    "\001\001\000\032\004\032\006\026\011\106\014\040\015" +
    "\042\020\044\021\034\022\036\023\043\024\023\027\033" +
    "\031\024\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\034\004\032" +
    "\006\026\010\132\011\025\014\040\015\042\020\044\021" +
    "\034\022\036\023\043\024\023\027\033\031\024\001\001" +
    "\000\032\004\032\006\026\011\106\014\040\015\042\020" +
    "\044\021\034\022\036\023\043\024\023\027\033\031\024" +
    "\001\001\000\002\001\001\000\002\001\001\000\006\006" +
    "\146\030\150\001\001\000\004\007\137\001\001\000\010" +
    "\006\141\024\142\030\144\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\006\012\112\030\055\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\004\024\163\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\006\006\166\030\167" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\010\016\174" +
    "\017\017\031\015\001\001\000\006\017\021\031\015\001" +
    "\001\000\002\001\001\000\034\004\032\006\026\010\177" +
    "\011\025\014\040\015\042\020\044\021\034\022\036\023" +
    "\043\024\023\027\033\031\024\001\001\000\032\004\032" +
    "\006\026\011\106\014\040\015\042\020\044\021\034\022" +
    "\036\023\043\024\023\027\033\031\024\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\034\004" +
    "\032\006\026\010\204\011\025\014\040\015\042\020\044" +
    "\021\034\022\036\023\043\024\023\027\033\031\024\001" +
    "\001\000\032\004\032\006\026\011\106\014\040\015\042" +
    "\020\044\021\034\022\036\023\043\024\023\027\033\031" +
    "\024\001\001\000\002\001\001\000\002\001\001" });

  /** Access to <code>reduce_goto</code> table. */
  public short[][] reduce_table() {return _reduce_table;}

  /** Instance of action encapsulation class. */
  protected CUP$parser$actions action_obj;

  /** Action encapsulation object initializer. */
  protected void init_actions()
    {
      action_obj = new CUP$parser$actions(this);
    }

  /** Invoke a user supplied parse action. */
  public java_cup.runtime.Symbol do_action(
    int                        act_num,
    java_cup.runtime.lr_parser parser,
    java.util.Stack            stack,
    int                        top)
    throws java.lang.Exception
  {
    /* call code in generated class */
    return action_obj.CUP$parser$do_action(act_num, parser, stack, top);
  }

  /** Indicates start state. */
  public int start_state() {return 0;}
  /** Indicates start production. */
  public int start_production() {return 1;}

  /** <code>EOF</code> Symbol index. */
  public int EOF_sym() {return 0;}

  /** <code>error</code> Symbol index. */
  public int error_sym() {return 1;}




/** table of declared symbols -- contains production parts indexed by name */
private Hashtable<String, Integer> symT = new Hashtable<String, Integer>();
      

    public void report_error(String message, Object info) {
   
        /* Create a StringBuilder called 'm' with the string 'Error' in it. */
        StringBuilder m = new StringBuilder("Error");
   
        /* Check if the information passed to the method is the same
           type as the type java_cup.runtime.Symbol. */
        if (info instanceof java_cup.runtime.Symbol) {
            /* Declare a java_cup.runtime.Symbol object 's' with the
               information in the object info that is being typecasted
               as a java_cup.runtime.Symbol object. */
            java_cup.runtime.Symbol s = ((java_cup.runtime.Symbol) info);
   
            /* Check if the line number in the input is greater or
               equal to zero. */
            if (s.left >= 0) {                
                /* Add to the end of the StringBuilder error message
                   the line number of the error in the input. */
                m.append(" in line "+(s.left+1));   
                /* Check if the column number in the input is greater
                   or equal to zero. */
                if (s.right >= 0)                    
                    /* Add to the end of the StringBuilder error message
                       the column number of the error in the input. */
                    m.append(", column "+(s.right+1));
            }
        }
   
        /* Add to the end of the StringBuilder error message created in
           this method the message that was passed into this method. */
        m.append(" : "+message);
   
        /* Print the contents of the StringBuilder 'm', which contains
           an error message, out on a line. */
        System.err.println(m);
    }
   
    /* Change the method report_fatal_error so when it reports a fatal
       error it will display the line and column number of where the
       fatal error occurred in the input as well as the reason for the
       fatal error which is passed into the method in the object
       'message' and then exit.*/
    public void report_fatal_error(String message, Object info) {
        report_error(message, info);
        System.exit(1);
    }


/** Cup generated class to encapsulate user supplied action code.*/
@SuppressWarnings({"rawtypes", "unchecked", "unused"})
class CUP$parser$actions {
  private final parser parser;

  /** Constructor */
  CUP$parser$actions(parser parser) {
    this.parser = parser;
  }

  /** Method 0 with the actual generated action code for actions 0 to 300. */
  public final java_cup.runtime.Symbol CUP$parser$do_action_part00000000(
    int                        CUP$parser$act_num,
    java_cup.runtime.lr_parser CUP$parser$parser,
    java.util.Stack            CUP$parser$stack,
    int                        CUP$parser$top)
    throws java.lang.Exception
    {
      /* Symbol object for return from actions */
      java_cup.runtime.Symbol CUP$parser$result;

      /* select the action based on the action number */
      switch (CUP$parser$act_num)
        {
          /*. . . . . . . . . . . . . . . . . . . .*/
          case 0: // s ::= lista_funcao PROGRAM STARTPRG list_command ENDPRG 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("s",0, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-4)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 1: // $START ::= s EOF 
            {
              Object RESULT =null;
		int start_valleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).left;
		int start_valright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).right;
		Object start_val = (Object)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-1)).value;
		RESULT = start_val;
              CUP$parser$result = parser.getSymbolFactory().newSymbol("$START",0, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          /* ACCEPT */
          CUP$parser$parser.done_parsing();
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 2: // list_command ::= list_command command 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("list_command",6, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 3: // list_command ::= command 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("list_command",6, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 4: // leiaa ::= LEIA ID SEMI 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("leiaa",11, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 5: // list_vector ::= list_vector vector 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("list_vector",19, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 6: // list_vector ::= vector 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("list_vector",19, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 7: // vector ::= ID LCOL NUMBER RCOL 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("vector",18, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-3)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 8: // command ::= declare_variable 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("command",7, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 9: // command ::= assign 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("command",7, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 10: // command ::= writel 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("command",7, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 11: // command ::= iff 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("command",7, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 12: // command ::= enquanto 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("command",7, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 13: // command ::= paraa 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("command",7, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 14: // command ::= leiaa 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("command",7, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 15: // command ::= call_func 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("command",7, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 16: // command ::= retornoo 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("command",7, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 17: // writel ::= WRITELINE expr_part SEMI 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("writel",14, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 18: // iff ::= IFF expr_list THENN list_command ELSEE list_command ENDELSE 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("iff",16, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-6)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 19: // declare_variable ::= type assign 
            {
              Object RESULT =null;
		int tleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).left;
		int tright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).right;
		String t = (String)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-1)).value;
		System.out.println(t); 
              CUP$parser$result = parser.getSymbolFactory().newSymbol("declare_variable",15, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 20: // declare_variable ::= type list_vector SEMI 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("declare_variable",15, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 21: // declare_variable ::= type ID SEMI 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("declare_variable",15, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 22: // assign ::= ID ATTRIB expr SEMI 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("assign",10, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-3)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 23: // assign ::= vector ATTRIB expr SEMI 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("assign",10, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-3)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 24: // assign ::= ID ATTRIB call_func 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("assign",10, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 25: // assign ::= vector ATTRIB call_func 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("assign",10, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 26: // expr_list ::= expr_list expr_part 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("expr_list",9, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 27: // expr_list ::= expr_part 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("expr_list",9, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 28: // expr_part ::= expr 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("expr_part",8, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 29: // expr ::= expr PLUS expr 
            {
              String RESULT =null;
		int e1left = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).left;
		int e1right = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).right;
		String e1 = (String)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-2)).value;
		int e2left = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int e2right = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		String e2 = (String)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		 RESULT = e1 + "+" + e2; 
              CUP$parser$result = parser.getSymbolFactory().newSymbol("expr",22, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 30: // expr ::= expr MINUS expr 
            {
              String RESULT =null;
		int e1left = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).left;
		int e1right = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).right;
		String e1 = (String)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-2)).value;
		int e2left = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int e2right = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		String e2 = (String)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		 RESULT = e1 + "-" + e2; 
              CUP$parser$result = parser.getSymbolFactory().newSymbol("expr",22, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 31: // expr ::= expr TIMES expr 
            {
              String RESULT =null;
		int e1left = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).left;
		int e1right = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).right;
		String e1 = (String)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-2)).value;
		int e2left = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int e2right = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		String e2 = (String)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		 RESULT = e1 + "*" + e2; 
              CUP$parser$result = parser.getSymbolFactory().newSymbol("expr",22, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 32: // expr ::= expr DIVIDE expr 
            {
              String RESULT =null;
		int e1left = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).left;
		int e1right = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).right;
		String e1 = (String)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-2)).value;
		int e2left = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int e2right = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		String e2 = (String)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		 RESULT = e1 + "/" + e2; 
              CUP$parser$result = parser.getSymbolFactory().newSymbol("expr",22, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 33: // expr ::= expr GREATER expr 
            {
              String RESULT =null;
		int e1left = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).left;
		int e1right = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).right;
		String e1 = (String)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-2)).value;
		int e2left = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int e2right = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		String e2 = (String)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		 RESULT = e1 + ">" + e2; 
              CUP$parser$result = parser.getSymbolFactory().newSymbol("expr",22, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 34: // expr ::= expr EQUALS expr 
            {
              String RESULT =null;
		int e1left = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).left;
		int e1right = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).right;
		String e1 = (String)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-2)).value;
		int e2left = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int e2right = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		String e2 = (String)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		 RESULT = e1 + "=" + e2; 
              CUP$parser$result = parser.getSymbolFactory().newSymbol("expr",22, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 35: // expr ::= expr LESS expr 
            {
              String RESULT =null;
		int e1left = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).left;
		int e1right = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).right;
		String e1 = (String)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-2)).value;
		int e2left = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int e2right = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		String e2 = (String)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		 RESULT = e1 + "<" + e2; 
              CUP$parser$result = parser.getSymbolFactory().newSymbol("expr",22, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 36: // expr ::= expr EE expr 
            {
              String RESULT =null;
		int e1left = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).left;
		int e1right = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).right;
		String e1 = (String)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-2)).value;
		int e2left = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int e2right = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		String e2 = (String)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		 RESULT = e1 + "&&" + e2; 
              CUP$parser$result = parser.getSymbolFactory().newSymbol("expr",22, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 37: // expr ::= expr OUU expr 
            {
              String RESULT =null;
		int e1left = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).left;
		int e1right = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).right;
		String e1 = (String)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-2)).value;
		int e2left = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int e2right = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		String e2 = (String)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		 RESULT = e1 + "||" + e2; 
              CUP$parser$result = parser.getSymbolFactory().newSymbol("expr",22, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 38: // expr ::= LPAREN expr RPAREN 
            {
              String RESULT =null;
		int e2left = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).left;
		int e2right = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).right;
		String e2 = (String)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-1)).value;
		 RESULT = "(" + e2 + ")"; 
              CUP$parser$result = parser.getSymbolFactory().newSymbol("expr",22, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 39: // expr ::= ID 
            {
              String RESULT =null;
		int idleft = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int idright = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		String id = (String)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		 RESULT = id;
              CUP$parser$result = parser.getSymbolFactory().newSymbol("expr",22, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 40: // expr ::= NUMBER 
            {
              String RESULT =null;
		int nleft = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int nright = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		String n = (String)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		 RESULT = n; 
              CUP$parser$result = parser.getSymbolFactory().newSymbol("expr",22, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 41: // expr ::= FLOAT 
            {
              String RESULT =null;
		int fleft = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int fright = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		String f = (String)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		 RESULT = f; 
              CUP$parser$result = parser.getSymbolFactory().newSymbol("expr",22, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 42: // call_func ::= ID LPAREN param_func RPAREN SEMI 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("call_func",4, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-4)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 43: // param_func ::= param_func expr 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("param_func",5, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 44: // param_func ::= param_func vector 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("param_func",5, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 45: // param_func ::= param_func call_func 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("param_func",5, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 46: // param_func ::= 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("param_func",5, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 47: // enquanto ::= ENQUANTO expr_part FACA list_command FIMENQUANTO 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("enquanto",17, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-4)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 48: // paraa ::= PARA ID DE NUMBER ATE NUMBER PASSO NUMBER FACA list_command FIMPARA 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("paraa",21, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-10)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 49: // type ::= DECFLOAT 
            {
              String RESULT =null;
		int tleft = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int tright = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		Object t = (Object)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		RESULT = "float";
              CUP$parser$result = parser.getSymbolFactory().newSymbol("type",23, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 50: // type ::= DECLINT 
            {
              String RESULT =null;
		int tleft = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int tright = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		Object t = (Object)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		 RESULT = "int"; 
              CUP$parser$result = parser.getSymbolFactory().newSymbol("type",23, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 51: // lista_funcao ::= lista_funcao func 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("lista_funcao",1, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 52: // lista_funcao ::= func 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("lista_funcao",1, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 53: // lista_funcao ::= 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("lista_funcao",1, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 54: // func ::= FUNCAO type ID LPAREN list_param RPAREN FUNCAOINI list_command FUNCAOFIM 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("func",20, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-8)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 55: // func ::= FUNCAO ID LPAREN list_param RPAREN FUNCAOINI list_command FUNCAOFIM 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("func",20, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-7)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 56: // retornoo ::= RETORNO expr_list SEMI 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("retornoo",2, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 57: // param ::= type ID 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("param",13, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 58: // list_param ::= list_param param 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("list_param",12, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 59: // list_param ::= param 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("list_param",12, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 60: // list_param ::= 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("list_param",12, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /* . . . . . .*/
          default:
            throw new Exception(
               "Invalid action number "+CUP$parser$act_num+"found in internal parse table");

        }
    } /* end of method */

  /** Method splitting the generated action code into several parts. */
  public final java_cup.runtime.Symbol CUP$parser$do_action(
    int                        CUP$parser$act_num,
    java_cup.runtime.lr_parser CUP$parser$parser,
    java.util.Stack            CUP$parser$stack,
    int                        CUP$parser$top)
    throws java.lang.Exception
    {
              return CUP$parser$do_action_part00000000(
                               CUP$parser$act_num,
                               CUP$parser$parser,
                               CUP$parser$stack,
                               CUP$parser$top);
    }
}

}
