
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20141204 (SVN rev 60)
//----------------------------------------------------

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int ATTRIB = 25;
  public static final int DIVIDE = 5;
  public static final int FUNCAO = 32;
  public static final int FIMENQUANTO = 37;
  public static final int DE = 27;
  public static final int EQUALS = 8;
  public static final int FUNCAOFIM = 34;
  public static final int LPAREN = 6;
  public static final int GREATER = 9;
  public static final int FUNCAOINI = 33;
  public static final int LESS = 10;
  public static final int MINUS = 3;
  public static final int PASSO = 35;
  public static final int E = 20;
  public static final int RPAREN = 7;
  public static final int THENN = 22;
  public static final int RCOL = 17;
  public static final int OU = 21;
  public static final int ATE = 28;
  public static final int ENDPRG = 13;
  public static final int PLUS = 2;
  public static final int ID = 38;
  public static final int ELSEE = 23;
  public static final int EOF = 0;
  public static final int STARTPRG = 12;
  public static final int ENDELSE = 24;
  public static final int error = 1;
  public static final int PROGRAM = 11;
  public static final int ENQUANTO = 31;
  public static final int NUMBER = 39;
  public static final int FIMPARA = 30;
  public static final int FACA = 36;
  public static final int TIMES = 4;
  public static final int WRITELINE = 14;
  public static final int LEIA = 29;
  public static final int DECLINT = 15;
  public static final int LCOL = 18;
  public static final int DECFLOAT = 16;
  public static final int PARA = 26;
  public static final int IFF = 19;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "PLUS",
  "MINUS",
  "TIMES",
  "DIVIDE",
  "LPAREN",
  "RPAREN",
  "EQUALS",
  "GREATER",
  "LESS",
  "PROGRAM",
  "STARTPRG",
  "ENDPRG",
  "WRITELINE",
  "DECLINT",
  "DECFLOAT",
  "RCOL",
  "LCOL",
  "IFF",
  "E",
  "OU",
  "THENN",
  "ELSEE",
  "ENDELSE",
  "ATTRIB",
  "PARA",
  "DE",
  "ATE",
  "LEIA",
  "FIMPARA",
  "ENQUANTO",
  "FUNCAO",
  "FUNCAOINI",
  "FUNCAOFIM",
  "PASSO",
  "FACA",
  "FIMENQUANTO",
  "ID",
  "NUMBER"
  };
}

